name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # This specifies the distribution
        java-version: 17
        java-package: jdk
        architecture: x64
        check-latest: false
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Run tests
      run: mvn test
      
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
          -Dsonar.projectKey=demo \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://18.221.86.34:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
