name: CI Pipeline

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

jobs:
  sonar:
    uses: SuryaHR/Demo-app/.github/workflows/ci.yml@main
    with:
      projectKey: Insurance-Backend
      projectToken: sqp_ed94b7f4b072494737ca2bb8e3e58e39170825dd
      sourceDir: './src'
